In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as pp

In [2]:
data = []
with open("classes_data.txt") as f:
    for line in f.readlines():
        line = list(map(float, line.strip().split(" ")))
        data.append(line)

data = np.matrix(data)

In [3]:
ds = pd.DataFrame(data, columns=["x1", "x2", "x", "y"])

In [4]:
ds.head()

x1     x2      x    y
0  186.0  206.0  200.0  0.0
1  186.0  206.0  200.0  0.0
2  185.0  203.0  200.0  0.0
3  185.0  203.0  200.0  0.0
4  185.0  203.0  200.0  0.0

In [5]:
from sklearn.model_selection import train_test_split
X = ds[["x1", "x2", "x"]]
y = ds["y"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [6]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.72
Accuracy of Logistic regression classifier on test set: 0.81


/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [7]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.98
Accuracy of Decision Tree classifier on test set: 0.95


In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.93
Accuracy of K-NN classifier on test set: 0.90


In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

Accuracy of LDA classifier on training set: 0.72
Accuracy of LDA classifier on test set: 0.79


In [10]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.66
Accuracy of GNB classifier on test set: 0.70


In [11]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Accuracy of SVM classifier on training set: 0.97
Accuracy of SVM classifier on test set: 0.89


/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [56]:
tmp = np.append(data, data[:, -1] == -1, axis=1)
tmp = np.append(tmp, data[:, -1] == 0, axis=1)
d1 = np.append(tmp, data[:, -1] == 1, axis=1)

In [55]:
import math
import torch
import torch.nn.functional as F
import numpy as np
from torch import nn, optim

In [100]:
X = torch.tensor(d1[:, 0:3], dtype=torch.float)
y = torch.tensor(d1[:, 4:], dtype=torch.float)

counter = 0
for i in range(X.shape[0]):
    if y[i, 0] == 1:
        print(X[i, :], y[i, :])
        counter += 1
        if counter == 5:
            break;
            
counter = 0
for i in range(X.shape[0]):
    if y[i, 1] == 1:
        print(X[i, :], y[i, :])
        counter += 1
        if counter == 5:
            break;    
            
counter = 0
for i in range(X.shape[0]):
    if y[i, 2] == 1:
        print(X[i, :], y[i, :])
        counter += 1
        if counter == 5:
            break;            

tensor([184., 186., 199.]) tensor([1., 0., 0.])
tensor([184., 185., 198.]) tensor([1., 0., 0.])
tensor([184., 185., 197.]) tensor([1., 0., 0.])
tensor([184., 185., 196.]) tensor([1., 0., 0.])
tensor([185., 184., 195.]) tensor([1., 0., 0.])
tensor([186., 206., 200.]) tensor([0., 1., 0.])
tensor([186., 206., 200.]) tensor([0., 1., 0.])
tensor([185., 203., 200.]) tensor([0., 1., 0.])
tensor([185., 203., 200.]) tensor([0., 1., 0.])
tensor([185., 203., 200.]) tensor([0., 1., 0.])
tensor([205., 204., 132.]) tensor([0., 0., 1.])
tensor([205., 204., 133.]) tensor([0., 0., 1.])
tensor([205., 204., 134.]) tensor([0., 0., 1.])
tensor([204., 205., 135.]) tensor([0., 0., 1.])
tensor([204., 205., 136.]) tensor([0., 0., 1.])


In [178]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(3, 2),
            nn.ReLU(),
            nn.Linear(2, 3)
        )

    def forward(self, xb):
        return self.model(xb)

In [179]:
model = Net()
lr = 1e-6
opt = optim.SGD(model.parameters(), lr=lr)
loss_func = F.mse_loss

In [180]:
n = X.size()[0]

bs = 50

for epoch in range(10000):
    for i in range((n - 1) // bs + 1):
        start_i = i * bs
        end_i = start_i + bs
        xb = X[start_i:end_i]
        yb = y[start_i:end_i]
        pred = model(xb)
        loss = loss_func(pred, yb)
        loss.backward()
        opt.step()
        opt.zero_grad()
        
    if epoch % 500 == 0:
        print(loss)

tensor(27.8991, grad_fn=<MseLossBackward>)
tensor(0.2319, grad_fn=<MseLossBackward>)
tensor(0.2300, grad_fn=<MseLossBackward>)
tensor(0.2282, grad_fn=<MseLossBackward>)
tensor(0.2264, grad_fn=<MseLossBackward>)
tensor(0.2246, grad_fn=<MseLossBackward>)
tensor(0.2228, grad_fn=<MseLossBackward>)
tensor(0.2211, grad_fn=<MseLossBackward>)
tensor(0.2194, grad_fn=<MseLossBackward>)
tensor(0.2177, grad_fn=<MseLossBackward>)
tensor(0.2160, grad_fn=<MseLossBackward>)
tensor(0.2144, grad_fn=<MseLossBackward>)
tensor(0.2128, grad_fn=<MseLossBackward>)
tensor(0.2112, grad_fn=<MseLossBackward>)
tensor(0.2096, grad_fn=<MseLossBackward>)
tensor(0.2081, grad_fn=<MseLossBackward>)
tensor(0.2066, grad_fn=<MseLossBackward>)
tensor(0.2051, grad_fn=<MseLossBackward>)
tensor(0.2036, grad_fn=<MseLossBackward>)
tensor(0.2021, grad_fn=<MseLossBackward>)


In [181]:
# left
print(model(torch.tensor([184., 186., 199.], dtype=torch.float)))
# straight
print(model(torch.tensor([185., 203., 200.], dtype=torch.float)))
# right
print(model(torch.tensor([205., 204., 134.], dtype=torch.float)))

tensor([-0.3715,  0.4477,  0.3988], grad_fn=<AddBackward0>)
tensor([-0.3715,  0.4477,  0.3988], grad_fn=<AddBackward0>)
tensor([-0.3715,  0.4477,  0.3988], grad_fn=<AddBackward0>)
